- src/main/resources/templates/ReceivingProcess.html
- src/main/resources/templates/StatusManagementReport.html
- src/main/resources/templates/TradingStatement.html
입고처리: 더미데이터추가 // 새로운 더미데이터에 따른 모달창을 추가X(코드 너무 길어짐)
거래명세서: 다운로드 열 삭제
> <chore> 현황관리:발주서가 많을시 스크롤 처리

- src/main/resources/templates/ReceivingProcessModal.html
- src/main/resources/templates/TradingStatementModal.html
> <chore> 모달창.html이 안올가서 추가

- src/main/resources/static/css/order.css
- src/main/resources/templates/ProductSelect.html
- src/main/resources/templates/orderRegister.html
<feat>ProductSelect.html에 등록 버튼 추가, 클릭 시 해당 품목이 이동하는 페이지에 대해 알려준 후 해당 품목은 화면에서 사라진다. <feat>orderRegister.html과 ProductSelect.html에 품목마다 취소 버튼 추가, 클릭 시 해당 품목이 이동하는 페이지에 대해 알려준 후 해당 품목은 화면에서 사라진다. <chore>orderRegister.html의 등록 버튼을 발행 버튼으로 변경하고 클릭 시 발행 여부에 대한 확인창이 뜨며, 확인 시 발행되었다는 알림 이후 현황 관리 리포트 페이지로 이동한다.
> <chore>css의 .btn이 충돌하여 발생하는 문제(버튼 크기의 변경) 해결

- src/main/resources/static/js/StatusManagementReport.js
- src/main/resources/templates/ReceivingProcess.html
- src/main/resources/templates/StatusManagementReport.html
- src/main/resources/templates/TradingStatement.html
입고처리: 발주서 기준을 품목별로 수정 및 데이터 각 품목 데이터 전송 확인
거래명세서: 발주코드열 삭제 , 발주서 기준은 현상유지
> <chore> 품목 현황 관리 리포트: 발주서 기준을 품목별로 수정 및 그래프를 품목별로 수정

- src/main/resources/static/css/total.css
- src/main/resources/static/js/total.js
- src/main/resources/templates/ContractRegistration.html
- src/main/resources/templates/TotalPage.html
- src/main/resources/templates/orderInspect1_1.html
- src/main/resources/templates/orderInspect1_2.html
- src/main/resources/templates/orderInspect4.html
- src/main/resources/templates/orderList.html
- src/main/resources/templates/stockDelivery.html
- src/main/resources/templates/total.html
기존 발주 상태 중 미검수를 클릭하면 새로운 탭에서 생성하여 다른 화면으로 이동하지 않게 변경
진척 검수 등록 화면에서 진척검수 일정 등록 버튼은 수정과 삭제가 가능한 버튼으로 변경
맨 하단에는 진척 검수 일정을 추가할 수 있는 칸을 추가적으로 생성하도록 구현
3. 추가적인 진척 검수 창이 생성 되면 기존의 검수 수정 버튼과 삭제 버튼을 비활성화 시키고 만약 진척 검수가 완료시 모든 버튼을 비활성화
> <chore> 진척검수  변경 사항

- src/main/resources/static/js/order.js
- src/main/resources/static/js/total.js
- src/main/resources/templates/orderInspect1_1.html
> <chore>진척 검사 등록 후 수정버튼 누르면 수정버튼을 저장 버튼으로 변경되게 수정

- src/main/java/com/example/tae/entity/Order/Order.java
- src/main/resources/static/css/order.css
- src/main/resources/static/js/order.js
- src/main/resources/templates/orderList.html
- src/main/resources/templates/orderListPopup.html
<feat>분리된 팝업창 페이지 orderListPopup.html 생성
> <chore>orderList.html의 팝업창을 분리되게 order.css와 order.js와 함께 수정

- src/main/java/com/example/tae/controller/OrderController.java
- src/main/java/com/example/tae/entity/Order/Order.java
- src/main/java/com/example/tae/entity/ReleaseProcess/ReleaseProcess.java
- src/main/java/com/example/tae/service/ReleaseProcessServiceImpl.java
- src/main/resources/static/css/order.css
- src/main/resources/static/js/order.js
- src/main/resources/templates/orderList.html
- src/main/resources/templates/orderListPopup.html
> <chore>orderListPopup.html의 세부 내용 수정

- src/main/java/com/example/tae/controller/BinController.java
- src/main/java/com/example/tae/entity/Product/Product.java
- src/main/java/com/example/tae/entity/Product/ProductProductonPlan.java
- src/main/java/com/example/tae/entity/TradingStatement/TradingStatement.java
- src/main/java/com/example/tae/repository/ProductRepository/ProductProudctionPlanRepository.java
- src/main/java/com/example/tae/repository/ProductRepository/ProductRepository.java
- src/main/java/com/example/tae/service/BinDummyService.java
- src/main/java/com/example/tae/service/BinDummyServiceImpl.java
- src/main/java/com/example/tae/service/BinService.java
- src/main/java/com/example/tae/service/BinServiceImpl.java
- src/main/java/com/example/tae/service/TradingStatementService.java
- src/main/resources/static/css/ALL.css
- src/main/resources/templates/ReceivingProcess.html
- src/test/java/com/example/tae/ProductRepositoryTest/ProductRepositoryTest.java
- src/test/java/com/example/tae/TradingServiceTest/TradingStatmentRepositoryTest.java
- src/test/java/com/example/tae/injectInfo/BinH2DBDummyInectionTest.java
그와 관련된 테스트코드
현황관리와 입고처리 서비스 단(BinService)을 생성
H2DB 테스트
<chore> css수정
> <feat> 제품명 엔티티와 제품생산계획 엔티티 생성

- src/main/java/com/example/tae/controller/OrderController.java
- src/main/java/com/example/tae/entity/Order/ProgressInspection.java
- src/main/java/com/example/tae/entity/Order/Purchase.java
- src/main/java/com/example/tae/repository/OrderRepository.java
- src/main/java/com/example/tae/repository/ProgressInspectionRepository.java
- src/main/java/com/example/tae/service/OrderService.java
- src/test/java/com/example/tae/OrderServiceTests/OrderRepositoryTests.java
<chore> OrderRepository 이동
<chore> OrderController 수정
<chore> 진척 검수 계획에 대한 테스트 실시
> <feat> 진척 검수를 위한 ProgressInspectionRepository 추가

- src/main/java/com/example/tae/entity/Contract/Contract.java
- src/main/java/com/example/tae/entity/ProcurementPlan/ProcurementPlan.java
- src/test/java/com/example/tae/RegistratioinTest/Repository/ContractRepositoryTest.java
- src/test/java/com/example/tae/RegistratioinTest/Repository/ProcurementPlanRepositoryTest.java
- src/test/java/com/example/tae/RegistratioinTest/Repository/ProductInfomationRepositoryTest.java
> <chore> 테스트 코드 변경 및 추가

- src/main/java/com/example/tae/controller/TradingStatementController.java
- src/main/java/com/example/tae/entity/TradingStatement/TradingStatementDTO.java
- src/main/java/com/example/tae/entity/TradingStatement/TradingStatementModalDTO.java
- src/main/java/com/example/tae/repository/ReceivingProcessingRepository.java
- src/main/java/com/example/tae/service/BinServiceImpl.java
- src/main/java/com/example/tae/service/TradingStatementService.java
- src/main/java/com/example/tae/service/TradingStatementServiceImpl.java
- src/main/resources/static/css/ALL.css
- src/main/resources/static/js/StatusManagementReport.js
- src/main/resources/static/js/TradingStatement.js
- src/main/resources/templates/TradingStatement.html
- src/main/resources/templates/TradingStatementModal.html
- src/test/java/com/example/tae/ReceivingRepositoyTest/receivecingTest.java
- src/test/java/com/example/tae/TradingServiceTest/TradingStatementServiceImplTest.java
- src/test/java/com/example/tae/TradingServiceTest/TradingStatmentRepositoryTest.java
<chore> 해당 발주서를 기준으로 목록을 보여주고에 각발주서 대한 거래명세서 그려지게(검색기능X) <bug> 거래명세서 인쇄시 비율이 작아지는 현상
> <feat> 현환관리리포토 그래프 동적으로 그려지게 수정

- src/main/java/com/example/tae/controller/BinController.java
- src/main/java/com/example/tae/repository/ReceivingProcessingRepository.java
- src/main/java/com/example/tae/repository/ReleaseRepository.java
- src/main/java/com/example/tae/service/BinService.java
- src/main/java/com/example/tae/service/BinServiceImpl.java
- src/main/resources/static/css/ALL.css
- src/main/resources/static/js/ReceivingProcessing.js
- src/main/resources/static/js/existence.js
- src/main/resources/templates/StatusManagementReport.html
- src/main/resources/templates/TradingStatement.html
> <chore> 입고처리 검색후 입고처리하면 검색된 화면 유지추가

- src/main/java/com/example/tae/entity/ReceivingProcessing/dto/ReceivingProcessingDTO.java
- src/main/java/com/example/tae/repository/ReceivingProcessingRepository.java
- src/main/java/com/example/tae/service/BinServiceImpl.java
- src/main/resources/static/js/ReceivingProcessing.js
- src/main/resources/static/js/StatusManagementReport.js
- src/main/resources/static/js/TradingStatement.js
- src/main/resources/templates/StatusManagementReport.html
- src/main/resources/templates/TradingStatement.html
입고처리 및 현환관리 및 거래명세서 그려지는 body이름 변경
> <chore> 현황관리 그래프및 리스트 수정

- src/main/java/com/example/tae/controller/OrderController.java
- src/main/java/com/example/tae/entity/Order/dto/OrderDTO.java
- src/main/java/com/example/tae/service/PurchaseService/OrderService.java
- src/main/java/com/example/tae/service/PurchaseService/OrderServiceImpl.java
- src/main/resources/static/css/order.css
- src/main/resources/static/css/total.css
- src/main/resources/static/js/existence.js
- src/main/resources/static/js/order.js
- src/main/resources/static/js/orderListPopup.js
- src/main/resources/static/js/orderRegister.js
- src/main/resources/static/js/total.js
- src/main/resources/templates/ProductInformationRegistration.html
- src/main/resources/templates/TotalPage.html
- src/main/resources/templates/existence.html
- src/main/resources/templates/orderInspect.html
- src/main/resources/templates/orderList.html
- src/main/resources/templates/orderListPopup.html
- src/main/resources/templates/orderRegister.html
- src/main/resources/templates/total.html
[<chore>재고 현황 리포트 수정](https://github.com/TAE-Trial-and-error/mit305/commit/af267527bcb04732897031d2675be66dd21da542)
@[1argeD](https://github.com/TAE-Trial-and-error/mit305/commits?author=1argeD)
1argeD committed yesterday
[Merge branch 'master' of](https://github.com/TAE-Trial-and-error/mit305/commit/4c03e54c7e11bd371712abef922ce9bfac060dda) https://github.com/1argeD/mit305
@[1argeD](https://github.com/TAE-Trial-and-error/mit305/commits?author=1argeD)
1argeD committed yesterday
[<chore>발주서 작성](https://github.com/TAE-Trial-and-error/mit305/commit/281808c8680614675df055085fed8eee2448e55a)
@[1argeD](https://github.com/TAE-Trial-and-error/mit305/commits?author=1argeD)
1argeD committed 16 hours ago
[Merge branch 'master' of](https://github.com/TAE-Trial-and-error/mit305/commit/0d1f58588b222abb …
> 1argeD committed

- src/main/java/com/example/tae/controller/ProjectPlaneController.java
- src/main/java/com/example/tae/repository/ProjectRepository/ProjectPlanRepository.java
- src/main/java/com/example/tae/service/ProjectService.java
- src/main/java/com/example/tae/service/ProjectServiceImpl.java
- src/main/resources/templates/ProjectPlan.html
조달계획이 등록된채로 수정을 하면
생산계획이 수정 가능해서
수정버튼을 비활성화-> 생산계획을 수정할려면 생산계획을 삭제하고 같은 날짜에 수량을 변경하여 재등록
> <chore>  생산계획 수정하기 완료O

- src/main/resources/static/css/ALL.css
- src/main/resources/static/css/Registration.css
- src/main/resources/static/js/ContractRegistration.js
- src/main/resources/static/js/ProcurementPlanRegistration.js
- src/main/resources/static/js/ProductInformationRegistration.js
- src/main/resources/templates/ContractRegistration.html
- src/main/resources/templates/ProcurementPlanRegistration.html
- src/main/resources/templates/ProductInformationRegistration.html
- src/main/resources/templates/TradingStatement.html
> <chore>  버튼을 제외 하고 기본적인 틀만 css 적용

- src/main/java/com/example/tae/controller/OrderController.java
- src/main/java/com/example/tae/controller/ProgressInspectorController.java
- src/main/java/com/example/tae/entity/Order/ProgressInspection.java
- src/main/java/com/example/tae/entity/Order/dto/OrderDTO.java
- src/main/java/com/example/tae/entity/Order/dto/ProgressInspectionDTO.java
- src/main/java/com/example/tae/service/PurchaseService/OrderService.java
- src/main/java/com/example/tae/service/PurchaseService/OrderServiceImpl.java
- src/main/java/com/example/tae/service/PurchaseService/ProgressInspectorService.java
- src/main/java/com/example/tae/service/PurchaseService/ProgressInspectorServiceImpl.java
- src/main/resources/static/js/order.js
- src/main/resources/static/js/orderRegister.js
- src/main/resources/static/js/total.js
- src/main/resources/templates/orderInspect.html
- src/main/resources/templates/orderList.html
> <chore> 진척검수 기존에 수행하지 않은 진척검수가 있어도 등록이 가능하도록 수정

- src/main/resources/templates/admin.html
- src/main/resources/templates/join.html
- src/main/resources/templates/memberList.html
<chore>join.html 디자인 추가
<chore>memberList.html 디자인 추가
> <chore>admin.html 디자인 추가

- src/main/java/com/example/tae/SecurityConfig.java
- src/main/java/com/example/tae/controller/ExistenceController.java
- src/main/java/com/example/tae/controller/StockController.java
- src/main/java/com/example/tae/entity/ReleaseProcess/Existence.java
- src/main/java/com/example/tae/entity/dto/ExistenceDTO.java
- src/main/java/com/example/tae/service/ReleaseProcessServiceImpl.java
- src/main/resources/static/js/existence.js
- src/main/resources/static/js/stockDelivery.js
- src/main/resources/templates/ContractRegistrationModal.html
[<chore> 재고 산출 쿠키 허용](https://github.com/TAE-Trial-and-error/mit305/commit/02390f5c19810f7294f2f907acc695c1897bf16d)
@[1argeD](https://github.com/TAE-Trial-and-error/mit305/commits?author=1argeD)
1argeD committed now
[Merge branch 'master' of](https://github.com/TAE-Trial-and-error/mit305/commit/4607b412f3bec9be6b76cf0b16a2dc998cf47a85) https://github.com/1argeD/mit305
> <chore> 재고 산출 쿠키 허용
